apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-exporter
  name: python-exporter
spec:
  ports:
  - name: server-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: exporter-port
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: python-exporter
  type: NodePort
status:
  loadBalancer: {}
